# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.45.0
    hooks:
    -   id: golangci-lint
